### ISSUE TITLE
Tailwind 3.0 support?

### ISSUE THREAD

**Issue by Mak0nz** [GeoffSelby/tailwind-highlightjs#1]
Hey, I'm new to tailwind. I noticed the wiki is using tailwind 2 for the tailwind.config.js
I was wondering if tailwind 3.0 is supported, and if yes, how you would go on about installing & configuring it.

I managed to install it using yarn, npm had an error about it requiring tailwind 2 when im using 3.

Thanks for the help.

**Comment by GeoffSelby** [comment]
Hey! Sorry this took so long. I just tagged and published V2. It is now fully compatible with Tailwind V3! Be sure to check out the updated usage instructions to set up the safelist with the JIT compiler so that your Highlight.js theme styles are generated.
